const ActionTypes = {
	UPDATE_USER: "UPDATE_USER",

	NAVIGATION_TOGGLE: "NAVIGATION_TOGGLE",
	NAVIGATION_POSITION: "NAVIGATION_POSITION",
	NAVIGATION_SET_ANCHOR: "NAVIGATION_SET_ANCHOR",
	
	SEARCH_SET_QUERY: "SEARCH_SET_QUERY",
	SEARCH_SET_IMAGE_RESULTS: "SEARCH_SET_IMAGE_RESULTS",
	SEARCH_SET_TEXT_RESULTS: "SEARCH_SET_TEXT_RESULTS",
};

export default ActionTypes;